### ISSUE TITLE
Failed to setup after update from 0.1.6 to 0.2.x

### ISSUE THREAD

**Issue by Qweua** [Patrick762/hassio-bluetti-bt#211]
Hi, 

If I try to update Bluetti BT integration it write in integration list Failed to setup. In integration setup button shows:
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

What I do wrong? Shouldn't update? Or?

EP600 battery. 

Currently rollback version again 🤷

Thanks.

**Comment by Qweua** [comment]
Latest 0.2.0 with same result 

Failed to set up:
Check the logs

Where this log?  :)

**Comment by Qweua** [comment]
Found in logs:


 File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3682, in async_create_flow
    return handler.async_get_options_flow(entry)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/config/custom_components/bluetti_bt/config_flow.py", line 122, in async_get_options_flow
    return OptionsFlowHandler(config_entry)
  File "/config/custom_components/bluetti_bt/config_flow.py", line 131, in __init__
    self.config_entry = config_entry
    ^^^^^^^^^^^^^^^^^
AttributeError: property 'config_entry' of 'OptionsFlowHandler' object has no setter

**Comment by jhagenk** [comment]
I also see the same. All devices are showing "failed to set up". 

I have two AC500 units, one AC300, and one EP800 that would normally be listed.

**Comment by TheMRX13** [comment]
Failed to setup here too. eB3A wirt encyption. Only thing what i can provide is

PollingCoordinator' object has no attribute 'reader

The ntegration for log cant acess my logs. Idk why

**Comment by Patrick762** [comment]
Do you also see the error `Device is unknown type` ?

The only early exit is here: https://github.com/Patrick762/hassio-bluetti-bt/blob/4844933b6c674f573fdf3a4dfa60900e3298d244/custom_components/bluetti_bt/coordinator.py#L40

**Comment by Patrick762** [comment]
@dgudim https://github.com/Patrick762/hassio-bluetti-bt/releases/tag/0.2.1-beta.3

**Comment by dgudim** [comment]
Amazing

**Comment by dgudim** [comment]
I am getting some weird readings in hass tho

From cli:
```
bluetti-read -m a8:46:74:0e:17:ca -e true -t EL30V2
Client created
Reader created

FieldName.DEVICE_TYPE: EL30V2
FieldName.DEVICE_SN: <SN>
FieldName.BATTERY_SOC: 83%
FieldName.DC_OUTPUT_POWER: 17W
FieldName.AC_OUTPUT_POWER: 383W
FieldName.DC_INPUT_POWER: 0W
FieldName.AC_INPUT_POWER: 606W
FieldName.AC_INPUT_VOLTAGE: 228.0V
```

In hass:

<img width="348" height="431" alt="Image" src="https://github.com/user-attachments/assets/d805110f-b31a-4413-9166-de33c15a04ed" />

**Comment by Patrick762** [comment]
I might have forgotten something. I'll look into it

**Comment by dgudim** [comment]
Thanks, no rush

**Comment by dgudim** [comment]
It says `No devices found` now 😅

**Comment by Qweua** [comment]
0.2.1-beta.4
After update still Failed to set up
If I remove device couldn't add again: No devices found

PS: EP600

**Comment by dgudim** [comment]
0.2.1-beta.6

Still 'No devices found'

**Comment by TheMRX13** [comment]
EB3A Started working but missing Controlles, AC Voltage , DC Voltage, ECO mode, Turbo mode and LED State.

Current Version: 0.2.1-beta.7

**Comment by goetzc** [comment]
> EB3A Started working but missing Controlles, AC Voltage , DC Voltage, ECO mode, Turbo mode and LED State.

Try fully removing the integration and re-adding it back. That worked for me and all sensors and controls showed up.

**Comment by shbatm** [comment]
I had to remove the device and wait for it to be found again for my AC300, but now I don't have any controls.

**Comment by TheMRX13** [comment]
> Controls will take more time. Encryption messed up a lot sadly

Alright. Whats with the other entities?

**Comment by TheMRX13** [comment]
> @TheMRX13 Those should be working already. Can you test if those are also missing with [bluetti-read](https://github.com/Patrick762/bluetti-bt-lib?tab=readme-ov-file#read-device-data-for-supported-devices)?

I can do that tomrorrow! Im not at home right now.

**Comment by Patrick762** [comment]
@TheMRX13 Do you mean to only use the name of the enum instead of "Class.NAME"?

**Comment by TheMRX13** [comment]
> Like this?

Yes! i Think this helps:
```
LedMode.OFF = Off
LedMode.LOW =  Low
LedMode.HIGH = High
LedMode.SOS = SOS 
```
```
ChargingMode.SILENT = Silent
ChargingMode.STANDARD = Standart
ChargingMode.TURBO = Turbo
```

> FieldName.CTRL_ECO_TIME_MODE: HOURS1

i Would Prefer "1HOURS"

**Comment by TheMRX13** [comment]
> I can only do this right now (otherwise there would be more mappings):

i Agree to this. Also To the Frequenc. your Second Entity!

**Comment by ItsMe00007** [comment]
I just upgraded from 0.1.6 to 0.2.1-beta.16 and all entities stay "unavailable":
Device is AC500+2xB300S.
I turned on debugging, but have not seen any specific entries for the Bluetti integration.
After downgrading to 0.1.6 everything works again.

Any ideas how to get the 0.2.1-beta.16 working with my AC500+2xB300S ? I don't use encryption.

**Comment by Patrick762** [comment]
You might have to remove the device first, then update. I only tested it with AC300.
If this doesn't work, please try to use the bluetti-bt-lib itself and see if this works

**Comment by ItsMe00007** [comment]
> [@ItsMe00007](https://github.com/ItsMe00007) data is not lost if you remove the device. Also you can re-add it with the same ID so that nothing breaks.
> 
> BTW, always remember to create a backup first.

How can I make sure that it is readded with the same id after deletion ?

**Comment by Kikou48** [comment]
Bonjour,

Je me sens un peut perdu! Je n'arrive plus à voir ma batterie EP760 depuis le passage à la version 0.2.0 et quand j'ai voulus retourner sur la version 0.1.6 , j'ai le même problème. 
Celas fais plus d'un an que je pouvais suivre le % de ma batterie avec HA et mes automatisations étaient bien fonctionnel, **alors encore pour votre travail**. 
Mais pour le moment je ne sais pas quel procédure suivre pour retrouver toute les fonctionnalité qu'il avait avant?
J'espère qu'une version stable sera à nouveau opérationnel ?
 
Merci encore pour le travail effectuer cordialement,

**Comment by specs32** [comment]
Same scenario on AC500 for me -> not detected after update from 0.1.6 to 0.2.1. trying to manually add the device results in "no device found", though the BT Adapter found the device "seconds ago" .

```
...
"name":"AC5002242000642383",
"rssi":-62,
...
"connectable":true,
"time":1768839710.0924702,
"tx_power":null,
...
```

log says :

``` 
This error originated from a custom integration.

Logger: bluetti_bt_lib.bluetooth.device_recognizer
Source: custom_components/bluetti_bt/config_flow.py:38
integration: Bluetti BT (documentation, issues)
First occurred: 5:07:58 PM (1 occurrence)
Last logged: 5:07:58 PM

Device has populated type_data with trash data 
```

and also : 

```
This error originated from a custom integration.

Logger: bluetti_bt_lib.bluetooth.device_reader.XX_XX_XX_XX_XX_A6
Source: custom_components/bluetti_bt/config_flow.py:38
integration: Bluetti BT (documentation, issues)
First occurred: 5:07:23 PM (2 occurrences)
Last logged: 5:07:48 PM

Timeout
```

**Comment by Spettacolo83** [comment]
Hi everyone! I experienced the same issue upgrading from v0.1.6 to v0.2.1 on Home Assistant 2026.2.3 with an AC300.

After investigating, I found the root cause: the config entry data from v0.1.6 doesn't contain the `use_encryption` field that v0.2.x expects. This causes `InitialDeviceConfig.has_values()` to return `False` (since `isinstance(None, bool)` is `False`), which makes the integration silently fail to start.

Additionally, `PollingCoordinator.__init__` can exit early without assigning `self.reader`, causing the `AttributeError: 'PollingCoordinator' object has no attribute 'reader'` that many of you have reported.

I've submitted a PR with a fix: #230

The fix:
- Defaults `use_encryption` to `False` when missing (backward compat with v0.1.6 config entries)
- Initializes `self.reader = None` to prevent the AttributeError
- Adds better error logging for debugging

Tested and confirmed working on HA 2026.2.3 with AC300.

**Comment by Qweua** [comment]
Hi @Patrick762 

Migration much better :)  Now it's works after update on ep600.

But found some issues. 
1. Some sensor change naming, for example, sensor.ep6002246000xxxxxx_ac_output_power_phase_1 to sensor.living_room_ep6002246000xxxxxx_ac_phase_1_power and etc. Not big problem, but have to change a lot of templates and dashboards (energy).

2. Main issue for me (have to rollback migration). For some reason sensor.living_room_ep6002246000xxxxxx_ac_phase_1_power (and 2, 3 phase) show value 65354 (or 65535). As I found problem with negative values. Real value for old version -2 (charging).

Is it possible to fix this? 

Thank you.
